In [11]:
import numpy as np
import random

In [12]:
def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

In [13]:
def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

In [14]:
def random_place(board, player):
	selection = possibilities(board)
	if (0,0) not in selection:
		if (0,1) not in selection and (0,2) in selection:
			current_loc=(0,2)
		elif(1,0) not in selection and (2,0) in selection:
			current_loc=(2,0)
		elif (1,1) not in selection and (2,2) in selection:
			current_loc=(2,2)
		elif (1,1) not in selection and (2,2) in selection:
			current_loc=(2,2)
		elif (0,2) not in selection and (0,1) in selection:
			current_loc=(0,1)
		elif(2,0) not in selection and (1,0) in selection:
			current_loc=(1,0)
		elif (2,2) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	elif (0,1) not in selection:
		if (0,2) not in selection and (0,0) in selection:
			current_loc=(0,0)
		if (1,1) not in selection and (2,1) in selection:
			current_loc=(2,1)
		else:
			current_loc = random.choice(selection)
	elif (0,2) not in selection:
		if (0,1) not in selection and (0,0) in selection:
			current_loc=(0,0)
		elif(1,2) not in selection and (2,2) in selection:
			current_loc=(2,2)
		elif (1,1) not in selection and (2,0) in selection:
			current_loc=(2,0)
		elif (1,1) not in selection and (2,0) in selection:
			current_loc=(2,0)
		elif (0,2) not in selection and (2,2) in selection:
			current_loc=(2,2)
		elif(2,0) not in selection and (1,1) in selection:
			current_loc=(1,1)
		elif (2,2) not in selection and (1,2) in selection:
			current_loc=(1,2)
		else:
			current_loc = random.choice(selection)
	elif (1,0) not in selection:
		if (1,1) not in selection and (1,2) in selection:
			current_loc=(1,2)
		if (1,2) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	elif (1,1) not in selection:
		if (0,1) not in selection and (2,1) in selection:
			current_loc=(2,1)
		if (0,0) not in selection and (2,2) in selection:
			current_loc=(2,2)
		if (0,2) not in selection and (2,0) in selection:
			current_loc=(2,0)
		if (2,1) not in selection and (0,1) in selection:
			current_loc=(0,1)
		if (2,2) not in selection and (0,0) in selection:
			current_loc=(0,0)
		if (2,0) not in selection and (0,2) in selection:
			current_loc=(0,2)
		else:
			current_loc = random.choice(selection)
	elif (1,2) not in selection:
		if (1,1) not in selection and (1,0) in selection:
			current_loc=(1,0)
		if (1,0) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	elif (2,0) not in selection:
		if (2,1) not in selection and (2,2) in selection:
			current_loc=(2,2)
		elif(1,0) not in selection and (0,0) in selection:
			current_loc=(0,0)
		elif (1,1) not in selection and (0,2) in selection:
			current_loc=(0,2)
		elif (2,2) not in selection and (2,1) in selection:
			current_loc=(2,1)
		elif (0,0) not in selection and (1,0) in selection:
			current_loc=(1,0)
		elif(0,2) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	elif (2,1) not in selection:
		if (1,1) not in selection and (0,1) in selection:
			current_loc=(0,1)
		if (0,1) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	elif (2,2) not in selection:
		if (2,1) not in selection and (2,0) in selection:
			current_loc=(2,0)
		elif(1,2) not in selection and (0,2) in selection:
			current_loc=(0,2)
		elif (1,1) not in selection and (0,0) in selection:
			current_loc=(0,0)
		elif (2,0) not in selection and (2,1) in selection:
			current_loc=(2,1)
		elif (0,2) not in selection and (1,2) in selection:
			current_loc=(1,2)
		elif(0,0) not in selection and (1,1) in selection:
			current_loc=(1,1)
		else:
			current_loc = random.choice(selection)
	else:
		current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

In [15]:
def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

In [16]:
def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

In [17]:
def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

In [18]:
def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

In [20]:
board, winner, counter = create_board(), 0, 1

while winner == 0:
    for player in [1, 2]:
        if player == 1:
            board = random_place(board, player)
        else:
            row,column=map(int,input("Enter the position you want to play").split())
            board[row][column]=player
        print("Board after " + str(counter) + " move")
        print(board)
        counter += 1
        winner = evaluate(board)
        if winner != 0:
            break

if winner==2:
    print("You won!")
elif winner==1:
    print("You Lost")

Board after 1 move
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Board after 2 move
[[2 0 0]
 [0 0 0]
 [1 0 0]]
Board after 3 move
[[2 0 0]
 [1 0 0]
 [1 0 0]]
Board after 4 move
[[2 0 2]
 [1 0 0]
 [1 0 0]]
Board after 5 move
[[2 1 2]
 [1 0 0]
 [1 0 0]]
Board after 6 move
[[2 1 2]
 [1 2 0]
 [1 0 0]]
Board after 7 move
[[2 1 2]
 [1 2 0]
 [1 0 1]]
Board after 8 move
[[2 1 2]
 [1 2 2]
 [1 0 1]]


UnboundLocalError: cannot access local variable 'current_loc' where it is not associated with a value